version: '3.4'

services:
  web:
    image: web:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_web$
    volumes:
      - C:\Users\Marion et Nicolas\source\repos\web\web:/app
      - C:\Users\Marion et Nicolas\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_web$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_web$ bin/Debug/netcoreapp2.0/web.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""

  web-tests:
    image: web-tests:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_web-tests$
    volumes:
      - C:\Users\Marion et Nicolas\source\repos\web\web:/app
      - C:\Users\Marion et Nicolas\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_web-tests$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_web-tests$ bin/Debug/netcoreapp2.0/web.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""

